version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data

  webapp:
    build: .
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '${PORT}:3000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
